[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "macarenaa558@gmail.com", email = "macarenaa558@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bcrypt<5",
    "fastapi>=0.141.1",
    "passlib[bcrypt]>=1.7.4",
    "python-dotenv>=1.2.3",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "tinydb>=4.9.0",
    "uvicorn>=0.52.3",
]

[project.scripts]
api = "api:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"



[tool.uv]
package = false
